### ISSUE TITLE
`CollectHathStatusMetricsJob` Stopped Working

### ISSUE THREAD

**Issue by misaka10055** [mixa3607/EH_metrics#3]
Hi,

Thanks for the awesome project. It all worked fine until a few hours ago, when the `CollectHathStatusMetricsJob` stopped working all of a sudden. Not sure if it's a problem on my end, or did the website change its layout.

Below are the error logs in reverse order:

```
2024/12/02 19:37:00,stdout,   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]]

2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.MetricsCollector.Jobs.CollectHathStatusMetricsJob.Execute(IJobExecutionContext context) in /ArkProjects.EHentai.MetricsCollector/Jobs/CollectHathStatusMetricsJob.cs:line 23
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Client.EHentaiClient.MyHomeApi.GetHathStatusAsync(CancellationToken ct)
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Models.Requests.HathStatusResponse.Parse(HtmlDocument doc)
2024/12/02 19:37:00,stdout,   --- End of inner exception stack trace --- [See nested exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
2024/12/02 19:37:00,stdout,   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.MetricsCollector.Jobs.CollectHathStatusMetricsJob.Execute(IJobExecutionContext context) in /ArkProjects.EHentai.MetricsCollector/Jobs/CollectHathStatusMetricsJob.cs:line 23
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Client.EHentaiClient.MyHomeApi.GetHathStatusAsync(CancellationToken ct)
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Models.Requests.HathStatusResponse.Parse(HtmlDocument doc)
2024/12/02 19:37:00,stdout, ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
2024/12/02 19:37:00,stdout,   --- End of inner exception stack trace --- [See nested exception: Quartz.SchedulerException: Job threw an unhandled exception.
2024/12/02 19:37:00,stdout,   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.MetricsCollector.Jobs.CollectHathStatusMetricsJob.Execute(IJobExecutionContext context) in /ArkProjects.EHentai.MetricsCollector/Jobs/CollectHathStatusMetricsJob.cs:line 23
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Client.EHentaiClient.MyHomeApi.GetHathStatusAsync(CancellationToken ct)
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Models.Requests.HathStatusResponse.Parse(HtmlDocument doc)
2024/12/02 19:37:00,stdout,   --- End of inner exception stack trace --- [See nested exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
2024/12/02 19:37:00,stdout,   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.MetricsCollector.Jobs.CollectHathStatusMetricsJob.Execute(IJobExecutionContext context) in /ArkProjects.EHentai.MetricsCollector/Jobs/CollectHathStatusMetricsJob.cs:line 23
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Client.EHentaiClient.MyHomeApi.GetHathStatusAsync(CancellationToken ct)
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Models.Requests.HathStatusResponse.Parse(HtmlDocument doc)
2024/12/02 19:37:00,stdout, ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
2024/12/02 19:37:00,stdout, ---> Quartz.SchedulerException: Job threw an unhandled exception.
2024/12/02 19:37:00,stdout, Quartz.JobExecutionException: Job threw an unhandled exception.
2024/12/02 19:37:00,stdout,"Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
2024/12/02 19:37:00,stdout,"[03:37:00 INF] Job eh.hath_status_metrics finished. Duration: 00:00:00.4469476, Refire: 0
"
2024/12/02 19:37:00,stdout,   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.MetricsCollector.Jobs.CollectHathStatusMetricsJob.Execute(IJobExecutionContext context) in /ArkProjects.EHentai.MetricsCollector/Jobs/CollectHathStatusMetricsJob.cs:line 23
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Client.EHentaiClient.MyHomeApi.GetHathStatusAsync(CancellationToken ct)
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Models.Requests.HathStatusResponse.Parse(HtmlDocument doc)
2024/12/02 19:37:00,stdout,   --- End of inner exception stack trace --- [See nested exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
2024/12/02 19:37:00,stdout,   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.MetricsCollector.Jobs.CollectHathStatusMetricsJob.Execute(IJobExecutionContext context) in /ArkProjects.EHentai.MetricsCollector/Jobs/CollectHathStatusMetricsJob.cs:line 23
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Client.EHentaiClient.MyHomeApi.GetHathStatusAsync(CancellationToken ct)
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Models.Requests.HathStatusResponse.Parse(HtmlDocument doc)
2024/12/02 19:37:00,stdout, ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
2024/12/02 19:37:00,stdout,Quartz.SchedulerException: Job threw an unhandled exception.
2024/12/02 19:37:00,stdout,[03:37:00 ERR] Job eh.hath_status_metrics threw an exception.
2024/12/02 19:37:00,stdout,   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.MetricsCollector.Jobs.CollectHathStatusMetricsJob.Execute(IJobExecutionContext context) in /ArkProjects.EHentai.MetricsCollector/Jobs/CollectHathStatusMetricsJob.cs:line 23
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Client.EHentaiClient.MyHomeApi.GetHathStatusAsync(CancellationToken ct)
2024/12/02 19:37:00,stdout,   at ArkProjects.EHentai.Api.Models.Requests.HathStatusResponse.Parse(HtmlDocument doc)
2024/12/02 19:37:00,stdout,System.IndexOutOfRangeException: Index was outside the bounds of the array.
2024/12/02 19:37:00,stdout,[03:37:00 ERR] Job eh.hath_status_metrics threw an unhandled Exception: 
```

**Comment by mixa3607** [comment]
@misaka10055 Hi/
Try `ghcr.io/mixa3607/eh_metrics:v1.3.0`
Changes: https://github.com/mixa3607/EH_metrics/releases/tag/v1.3.0

**Comment by misaka10055** [comment]
Worked perfectly now. Thanks a lot!
